spring:
  application:
    name: bff-ms
  graphql:
    graphiql:
      enabled: true
    path: /graphql
server:
  port: ${PORT}
logging:
  level:
    root: INFO
    com:
      netflix:
        discovery: DEBUG
    org:
      hibernate: DEBUG
      springframework: DEBUG
    feign: DEBUG
azure:
  function:
    user:
      rest:
        prod:
          create: ${AZ_FUNCTION_USER_CREATE}
          create-code: ${AZ_FN_CREATE_USER_KEY}
          get: ${AZ_FUNCTION_USER_GET}
          update: ${AZ_FUNCTION_USER_UPDATE}
          delete: ${AZ_FUNCTION_USER_DELETE}
          url: ${AZ_FUNCTION_URL}
        dev:
          url: ${AZ_FUNCTION_DEV_URL}
      graphql:
        prod:
          url: ${AZ_FUNCTION_GRAPHQL_URL}
        dev:
          url: ${AZ_FUNCTION_DEV_GRAPHQL_URL}
    role:
      rest:
        prod:
          create: ${AZ_FUNCTION_ROLE_CREATE}
          create-code: ${AZ_FN_CREATE_ROLE_KEY}
          get: ${AZ_FUNCTION_ROLE_GET}
          update: ${AZ_FUNCTION_ROLE_UPDATE}
          delete: ${AZ_FUNCTION_ROLE_DELETE}
          url: ${AZ_FUNCTION_URL}
        dev:
          url: ${AZ_FUNCTION_DEV_URL}
      graphql:
        prod:
          url: ${AZ_FUNCTION_GRAPHQL_URL}
        dev:
          url: ${AZ_FUNCTION_DEV_GRAPHQL_URL}
