spring:
  application:
    name: bff-ms
server:
  port: ${PORT}
logging:
  level:
    root: INFO
    com:
      netflix:
        discovery: DEBUG
    org:
      hibernate: DEBUG
      springframework: DEBUG
    feign: DEBUG
azure:
  function:
    user:
      prod:
        url: ${AZ_FUNCTION_USER_URL}
      dev:
        url: ${AZ_FUNCTION_USER_DEV_URL}
    role:
      prod:
        url: ${AZ_FUNCTION_ROLE_URL}
      dev:
        dev-url: ${AZ_FUNCTION_ROLE_DEV_URL}
