spring:
  application:
    name: bff-ms
  graphql:
    graphiql:
      enabled: true
    path: /graphql
server:
  port: ${PORT}
logging:
  level:
    root: INFO
    com:
      netflix:
        discovery: DEBUG
    org:
      hibernate: DEBUG
      springframework: DEBUG
    feign: DEBUG
azure:
  function:
    rest:
      user:
        url:
          create: ${AZ_FN_CREATE_USER}
          get: ${AZ_FN_GET_USER}
      role:
        url:
          get: ${AZ_FN_GET_ROLE}
    graphql:
      user:
        delete: ${AZ_FN_DELETE_USER_GQL}
      role:
        create: ${AZ_FN_CREATE_ROLE_GQL}
        update: ${AZ_FN_UPDATE_ROLE_GQL}
